version: '3'
services:
  server:
    container_name: app
    build: .
    ports:
      - ${PORT}:${PORT}
    networks:
      - server-db
    depends_on:
      - mongodb
    env_file:
      - .env
    restart: always
    command: npm run start:dev
  mongodb:
    image: mongo
    restart: always
    networks:
      - server-db
    env_file:
      - .env
    volumes:
      - db_data:/data/db
      - ./docker/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - db_config:/data/configdb
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}

networks:
  server-db:
    driver: bridge
volumes:
  db_data:
    driver: local
  db_config:
    driver: local
